/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CountA: typeof import('./src/components/CountA.vue')['default']
    CountB: typeof import('./src/components/CountB.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Index: typeof import('./src/components/show/Index.vue')['default']
    VanButton: typeof import('vant/es')['Button']
  }
}
